# -*- coding: utf-8 -*-
"""test_crud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cB1ZwLtHflkfmq0pMClctLk-hdLywYMO
"""


import pytest
from day_11 import create_table, insert, read, update, delete

@pytest.fixture
def setup_database():
    create_table()
    insert("John", 35)  # ID = 1
    yield
    delete(1)  # Cleanup

def test_insert_user(setup_database):
    insert("Jane", 28)  # ID = 2
    user = read(2)  # Fetch user by ID
    assert user is not None
    assert user[1] == "Jane"
    assert user[2] == 28

def test_update_user(setup_database):
    update("John Doe", 36, 1)
    user = read(1)  # Fetch user by ID
    assert user is not None
    assert user[1] == "John Doe"
    assert user[2] == 36

def test_delete_user(setup_database):
    delete(1)
    user = read(1)  # Try to fetch deleted user
    assert user is None  # User should not exist



